matrix:
  include:
    - language: android
      dist: trusty
      cache: yarn
      android:
        components:
          # use the latest revision of Android SDK Tools
          - tools
          - platform-tools

          # The BuildTools version used by your project
          - build-tools-28.0.3

          # The SDK version used to compile your project
          - android-28

          # Additional components
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
      licenses:
        - android-sdk-preview-license-.+
        - android-sdk-license-.+
        - google-gdk-license-.+
      before_install:
        - cd template
      install:
        - nvm install 14.5
        - yarn
      before_script:
        - cd android
      script:
        - ./gradlew assembleRelease

    - language: objective-c
      os: osx
      osx_image: xcode11.6
      podfile: template/ios/Podfile
      cache:
        - cocoapods
        - yarn
      before_install:
        - cd template
      install:
        - brew tap wix/brew
        - brew install applesimutils
        - gem install cocoapods
        - nvm install 14.5
        - yarn
      before_script:
        - cd ios
        - pod install
        - cd ..
      script:
        - npm run ios
